//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loki.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        public static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber pearl.
        /// </summary>
        public static string Amber_pearl {
            get {
                return ResourceManager.GetString("Amber pearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        public static string Ammo {
            get {
                return ResourceManager.GetString("Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient seed.
        /// </summary>
        public static string Ancient_seed {
            get {
                return ResourceManager.GetString("Ancient seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Atgeir.
        /// </summary>
        public static string Attach_Atgeir {
            get {
                return ResourceManager.GetString("Attach Atgeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes.
        /// </summary>
        public static string Axes {
            get {
                return ResourceManager.GetString("Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braided 1.
        /// </summary>
        public static string B_Braided_1 {
            get {
                return ResourceManager.GetString("B_Braided 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braided 2.
        /// </summary>
        public static string B_Braided_2 {
            get {
                return ResourceManager.GetString("B_Braided 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braided 3.
        /// </summary>
        public static string B_Braided_3 {
            get {
                return ResourceManager.GetString("B_Braided 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braided 4.
        /// </summary>
        public static string B_Braided_4 {
            get {
                return ResourceManager.GetString("B_Braided 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long 1.
        /// </summary>
        public static string B_Long_1 {
            get {
                return ResourceManager.GetString("B_Long 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long 2.
        /// </summary>
        public static string B_Long_2 {
            get {
                return ResourceManager.GetString("B_Long 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No beard.
        /// </summary>
        public static string B_No_beard {
            get {
                return ResourceManager.GetString("B_No beard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short 1.
        /// </summary>
        public static string B_Short_1 {
            get {
                return ResourceManager.GetString("B_Short 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short 2.
        /// </summary>
        public static string B_Short_2 {
            get {
                return ResourceManager.GetString("B_Short 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short 3.
        /// </summary>
        public static string B_Short_3 {
            get {
                return ResourceManager.GetString("B_Short 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick 1.
        /// </summary>
        public static string B_Thick_1 {
            get {
                return ResourceManager.GetString("B_Thick 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Character.
        /// </summary>
        public static string Backup_Character {
            get {
                return ResourceManager.GetString("Backup Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Restore.
        /// </summary>
        public static string Backup_Restore {
            get {
                return ResourceManager.GetString("Backup Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barley.
        /// </summary>
        public static string Barley {
            get {
                return ResourceManager.GetString("Barley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barley flour.
        /// </summary>
        public static string Barley_flour {
            get {
                return ResourceManager.GetString("Barley flour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barley wine base: Fire resistance.
        /// </summary>
        public static string Barley_wine_base__Fire_resistance {
            get {
                return ResourceManager.GetString("Barley wine base: Fire resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battleaxe.
        /// </summary>
        public static string Battleaxe {
            get {
                return ResourceManager.GetString("Battleaxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beard.
        /// </summary>
        public static string Beard {
            get {
                return ResourceManager.GetString("Beard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beech seeds.
        /// </summary>
        public static string Beech_seeds {
            get {
                return ResourceManager.GetString("Beech seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black metal.
        /// </summary>
        public static string Black_metal {
            get {
                return ResourceManager.GetString("Black metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black metal scrap.
        /// </summary>
        public static string Black_metal_scrap {
            get {
                return ResourceManager.GetString("Black metal scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackmetal atgeir.
        /// </summary>
        public static string Blackmetal_atgeir {
            get {
                return ResourceManager.GetString("Blackmetal atgeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackmetal axe.
        /// </summary>
        public static string Blackmetal_axe {
            get {
                return ResourceManager.GetString("Blackmetal axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob hair.
        /// </summary>
        public static string Blob_hair {
            get {
                return ResourceManager.GetString("Blob hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking.
        /// </summary>
        public static string Blocking {
            get {
                return ResourceManager.GetString("Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood pudding.
        /// </summary>
        public static string Blood_pudding {
            get {
                return ResourceManager.GetString("Blood pudding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloodbag.
        /// </summary>
        public static string Bloodbag {
            get {
                return ResourceManager.GetString("Bloodbag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueberries.
        /// </summary>
        public static string Blueberries {
            get {
                return ResourceManager.GetString("Blueberries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boar attack1.
        /// </summary>
        public static string boar_attack1 {
            get {
                return ResourceManager.GetString("boar attack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone fragments.
        /// </summary>
        public static string Bone_fragments {
            get {
                return ResourceManager.GetString("Bone fragments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        public static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bows.
        /// </summary>
        public static string Bows {
            get {
                return ResourceManager.GetString("Bows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braided 1.
        /// </summary>
        public static string Braided_1 {
            get {
                return ResourceManager.GetString("Braided 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braided 2.
        /// </summary>
        public static string Braided_2 {
            get {
                return ResourceManager.GetString("Braided 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braided 3.
        /// </summary>
        public static string Braided_3 {
            get {
                return ResourceManager.GetString("Braided 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braided 4.
        /// </summary>
        public static string Braided_4 {
            get {
                return ResourceManager.GetString("Braided 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bread.
        /// </summary>
        public static string Bread {
            get {
                return ResourceManager.GetString("Bread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze atgeir.
        /// </summary>
        public static string Bronze_atgeir {
            get {
                return ResourceManager.GetString("Bronze atgeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze axe.
        /// </summary>
        public static string Bronze_axe {
            get {
                return ResourceManager.GetString("Bronze axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze nails.
        /// </summary>
        public static string Bronze_nails {
            get {
                return ResourceManager.GetString("Bronze nails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze plate cuirass.
        /// </summary>
        public static string Bronze_plate_cuirass {
            get {
                return ResourceManager.GetString("Bronze plate cuirass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze plate leggings.
        /// </summary>
        public static string Bronze_plate_leggings {
            get {
                return ResourceManager.GetString("Bronze plate leggings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronzehead arrow.
        /// </summary>
        public static string Bronzehead_arrow {
            get {
                return ResourceManager.GetString("Bronzehead arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds.
        /// </summary>
        public static string Builds {
            get {
                return ResourceManager.GetString("Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        public static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable.
        /// </summary>
        public static string Consumable {
            get {
                return ResourceManager.GetString("Consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafts.
        /// </summary>
        public static string Crafts {
            get {
                return ResourceManager.GetString("Crafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crude bow.
        /// </summary>
        public static string Crude_bow {
            get {
                return ResourceManager.GetString("Crude bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customisation.
        /// </summary>
        public static string Customisation {
            get {
                return ResourceManager.GetString("Customisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draugr fang.
        /// </summary>
        public static string Draugr_fang {
            get {
                return ResourceManager.GetString("Draugr fang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fart.
        /// </summary>
        public static string fart {
            get {
                return ResourceManager.GetString("fart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finewood bow.
        /// </summary>
        public static string Finewood_bow {
            get {
                return ResourceManager.GetString("Finewood bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire arrow.
        /// </summary>
        public static string Fire_arrow {
            get {
                return ResourceManager.GetString("Fire arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire resistance barley wine.
        /// </summary>
        public static string Fire_resistance_barley_wine {
            get {
                return ResourceManager.GetString("Fire resistance barley wine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FireMagic.
        /// </summary>
        public static string FireMagic {
            get {
                return ResourceManager.GetString("FireMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flint axe.
        /// </summary>
        public static string Flint_axe {
            get {
                return ResourceManager.GetString("Flint axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flinthead arrow.
        /// </summary>
        public static string Flinthead_arrow {
            get {
                return ResourceManager.GetString("Flinthead arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost arrow.
        /// </summary>
        public static string Frost_arrow {
            get {
                return ResourceManager.GetString("Frost arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrostMagic.
        /// </summary>
        public static string FrostMagic {
            get {
                return ResourceManager.GetString("FrostMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        public static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Colour.
        /// </summary>
        public static string Hair_Colour {
            get {
                return ResourceManager.GetString("Hair Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        public static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heal.
        /// </summary>
        public static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helmet.
        /// </summary>
        public static string Helmet {
            get {
                return ResourceManager.GetString("Helmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huntsman bow.
        /// </summary>
        public static string Huntsman_bow {
            get {
                return ResourceManager.GetString("Huntsman bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron atgeir.
        /// </summary>
        public static string Iron_atgeir {
            get {
                return ResourceManager.GetString("Iron atgeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron axe.
        /// </summary>
        public static string Iron_axe {
            get {
                return ResourceManager.GetString("Iron axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron greaves.
        /// </summary>
        public static string Iron_greaves {
            get {
                return ResourceManager.GetString("Iron greaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron scale mail.
        /// </summary>
        public static string Iron_scale_mail {
            get {
                return ResourceManager.GetString("Iron scale mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ironhead arrow.
        /// </summary>
        public static string Ironhead_arrow {
            get {
                return ResourceManager.GetString("Ironhead arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        public static string Kills {
            get {
                return ResourceManager.GetString("Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knives.
        /// </summary>
        public static string Knives {
            get {
                return ResourceManager.GetString("Knives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leather pants.
        /// </summary>
        public static string Leather_pants {
            get {
                return ResourceManager.GetString("Leather pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leather tunic.
        /// </summary>
        public static string Leather_tunic {
            get {
                return ResourceManager.GetString("Leather tunic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        public static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long 1.
        /// </summary>
        public static string Long_1 {
            get {
                return ResourceManager.GetString("Long 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megingjord.
        /// </summary>
        public static string Megingjord {
            get {
                return ResourceManager.GetString("Megingjord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle arrow.
        /// </summary>
        public static string Needle_arrow {
            get {
                return ResourceManager.GetString("Needle arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hair.
        /// </summary>
        public static string No_hair {
            get {
                return ResourceManager.GetString("No hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian arrow.
        /// </summary>
        public static string Obsidian_arrow {
            get {
                return ResourceManager.GetString("Obsidian arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Handed Weapon.
        /// </summary>
        public static string One_Handed_Weapon {
            get {
                return ResourceManager.GetString("One Handed Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooze bomb.
        /// </summary>
        public static string Ooze_bomb {
            get {
                return ResourceManager.GetString("Ooze bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padded cuirass.
        /// </summary>
        public static string Padded_cuirass {
            get {
                return ResourceManager.GetString("Padded cuirass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padded greaves.
        /// </summary>
        public static string Padded_greaves {
            get {
                return ResourceManager.GetString("Padded greaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickaxes.
        /// </summary>
        public static string Pickaxes {
            get {
                return ResourceManager.GetString("Pickaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison arrow.
        /// </summary>
        public static string Poison_arrow {
            get {
                return ResourceManager.GetString("Poison arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polearms.
        /// </summary>
        public static string Polearms {
            get {
                return ResourceManager.GetString("Polearms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponytail 1.
        /// </summary>
        public static string Ponytail_1 {
            get {
                return ResourceManager.GetString("Ponytail 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponytail 2.
        /// </summary>
        public static string Ponytail_2 {
            get {
                return ResourceManager.GetString("Ponytail 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponytail 3.
        /// </summary>
        public static string Ponytail_3 {
            get {
                return ResourceManager.GetString("Ponytail 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponytail 4.
        /// </summary>
        public static string Ponytail_4 {
            get {
                return ResourceManager.GetString("Ponytail 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rag pants.
        /// </summary>
        public static string Rag_pants {
            get {
                return ResourceManager.GetString("Rag pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rag tunic.
        /// </summary>
        public static string Rag_tunic {
            get {
                return ResourceManager.GetString("Rag tunic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riding.
        /// </summary>
        public static string Riding {
            get {
                return ResourceManager.GetString("Riding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short 1.
        /// </summary>
        public static string Short_1 {
            get {
                return ResourceManager.GetString("Short 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short 2.
        /// </summary>
        public static string Short_2 {
            get {
                return ResourceManager.GetString("Short 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulder.
        /// </summary>
        public static string Shoulder {
            get {
                return ResourceManager.GetString("Shoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Swept 1.
        /// </summary>
        public static string Side_Swept_1 {
            get {
                return ResourceManager.GetString("Side Swept 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Swept 2.
        /// </summary>
        public static string Side_Swept_2 {
            get {
                return ResourceManager.GetString("Side Swept 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Swept 3.
        /// </summary>
        public static string Side_Swept_3 {
            get {
                return ResourceManager.GetString("Side Swept 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver arrow.
        /// </summary>
        public static string Silver_arrow {
            get {
                return ResourceManager.GetString("Silver arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Colour.
        /// </summary>
        public static string Skin_Colour {
            get {
                return ResourceManager.GetString("Skin Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Glow.
        /// </summary>
        public static string Skin_Glow {
            get {
                return ResourceManager.GetString("Skin Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slap.
        /// </summary>
        public static string slap {
            get {
                return ResourceManager.GetString("slap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slime throw.
        /// </summary>
        public static string slime_throw {
            get {
                return ResourceManager.GetString("slime throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneak.
        /// </summary>
        public static string Sneak {
            get {
                return ResourceManager.GetString("Sneak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spears.
        /// </summary>
        public static string Spears {
            get {
                return ResourceManager.GetString("Spears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone axe.
        /// </summary>
        public static string Stone_axe {
            get {
                return ResourceManager.GetString("Stone axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swim.
        /// </summary>
        public static string Swim {
            get {
                return ResourceManager.GetString("Swim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swords.
        /// </summary>
        public static string Swords {
            get {
                return ResourceManager.GetString("Swords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torch.
        /// </summary>
        public static string Torch {
            get {
                return ResourceManager.GetString("Torch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll leather pants.
        /// </summary>
        public static string Troll_leather_pants {
            get {
                return ResourceManager.GetString("Troll leather pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll leather tunic.
        /// </summary>
        public static string Troll_leather_tunic {
            get {
                return ResourceManager.GetString("Troll leather tunic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophy.
        /// </summary>
        public static string Trophy {
            get {
                return ResourceManager.GetString("Trophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Handed Weapon.
        /// </summary>
        public static string Two_Handed_Weapon {
            get {
                return ResourceManager.GetString("Two Handed Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unarmed.
        /// </summary>
        public static string Unarmed {
            get {
                return ResourceManager.GetString("Unarmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf armor chest.
        /// </summary>
        public static string Wolf_armor_chest {
            get {
                return ResourceManager.GetString("Wolf armor chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf armor legs.
        /// </summary>
        public static string Wolf_armor_legs {
            get {
                return ResourceManager.GetString("Wolf armor legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood arrow.
        /// </summary>
        public static string Wood_arrow {
            get {
                return ResourceManager.GetString("Wood arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Cutting.
        /// </summary>
        public static string Wood_Cutting {
            get {
                return ResourceManager.GetString("Wood Cutting", resourceCulture);
            }
        }
    }
}
