//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loki.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amber과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amber pearl과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Amber_pearl {
            get {
                return ResourceManager.GetString("Amber pearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ammo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ammo {
            get {
                return ResourceManager.GetString("Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ancient seed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ancient_seed {
            get {
                return ResourceManager.GetString("Ancient seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attach Atgeir과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Attach_Atgeir {
            get {
                return ResourceManager.GetString("Attach Atgeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Axes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Axes {
            get {
                return ResourceManager.GetString("Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braided 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Braided_1 {
            get {
                return ResourceManager.GetString("B_Braided 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braided 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Braided_2 {
            get {
                return ResourceManager.GetString("B_Braided 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braided 3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Braided_3 {
            get {
                return ResourceManager.GetString("B_Braided 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braided 4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Braided_4 {
            get {
                return ResourceManager.GetString("B_Braided 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Long_1 {
            get {
                return ResourceManager.GetString("B_Long 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Long_2 {
            get {
                return ResourceManager.GetString("B_Long 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No beard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_No_beard {
            get {
                return ResourceManager.GetString("B_No beard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Short_1 {
            get {
                return ResourceManager.GetString("B_Short 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Short_2 {
            get {
                return ResourceManager.GetString("B_Short 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short 3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Short_3 {
            get {
                return ResourceManager.GetString("B_Short 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thick 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string B_Thick_1 {
            get {
                return ResourceManager.GetString("B_Thick 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Backup_Character {
            get {
                return ResourceManager.GetString("Backup Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Restore과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Backup_Restore {
            get {
                return ResourceManager.GetString("Backup Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Barley과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Barley {
            get {
                return ResourceManager.GetString("Barley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Barley flour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Barley_flour {
            get {
                return ResourceManager.GetString("Barley flour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Barley wine base: Fire resistance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Barley_wine_base__Fire_resistance {
            get {
                return ResourceManager.GetString("Barley wine base: Fire resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battleaxe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Battleaxe {
            get {
                return ResourceManager.GetString("Battleaxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Beard {
            get {
                return ResourceManager.GetString("Beard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beech seeds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Beech_seeds {
            get {
                return ResourceManager.GetString("Beech seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black metal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Black_metal {
            get {
                return ResourceManager.GetString("Black metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black metal scrap과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Black_metal_scrap {
            get {
                return ResourceManager.GetString("Black metal scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blackmetal atgeir과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Blackmetal_atgeir {
            get {
                return ResourceManager.GetString("Blackmetal atgeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blackmetal axe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Blackmetal_axe {
            get {
                return ResourceManager.GetString("Blackmetal axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blob hair과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Blob_hair {
            get {
                return ResourceManager.GetString("Blob hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blocking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Blocking {
            get {
                return ResourceManager.GetString("Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blood pudding과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Blood_pudding {
            get {
                return ResourceManager.GetString("Blood pudding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bloodbag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bloodbag {
            get {
                return ResourceManager.GetString("Bloodbag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blueberries과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Blueberries {
            get {
                return ResourceManager.GetString("Blueberries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   boar attack1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string boar_attack1 {
            get {
                return ResourceManager.GetString("boar attack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bone fragments과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bone_fragments {
            get {
                return ResourceManager.GetString("Bone fragments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bows {
            get {
                return ResourceManager.GetString("Bows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braided 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Braided_1 {
            get {
                return ResourceManager.GetString("Braided 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braided 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Braided_2 {
            get {
                return ResourceManager.GetString("Braided 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braided 3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Braided_3 {
            get {
                return ResourceManager.GetString("Braided 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braided 4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Braided_4 {
            get {
                return ResourceManager.GetString("Braided 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bread과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bread {
            get {
                return ResourceManager.GetString("Bread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bronze과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bronze atgeir과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bronze_atgeir {
            get {
                return ResourceManager.GetString("Bronze atgeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bronze axe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bronze_axe {
            get {
                return ResourceManager.GetString("Bronze axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bronze nails과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bronze_nails {
            get {
                return ResourceManager.GetString("Bronze nails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bronze plate cuirass과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bronze_plate_cuirass {
            get {
                return ResourceManager.GetString("Bronze plate cuirass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bronze plate leggings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bronze_plate_leggings {
            get {
                return ResourceManager.GetString("Bronze plate leggings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bronzehead arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bronzehead_arrow {
            get {
                return ResourceManager.GetString("Bronzehead arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Builds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Builds {
            get {
                return ResourceManager.GetString("Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clubs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consumable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Consumable {
            get {
                return ResourceManager.GetString("Consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crafts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Crafts {
            get {
                return ResourceManager.GetString("Crafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crude bow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Crude_bow {
            get {
                return ResourceManager.GetString("Crude bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customisation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Customisation {
            get {
                return ResourceManager.GetString("Customisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deaths과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draugr fang과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Draugr_fang {
            get {
                return ResourceManager.GetString("Draugr fang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string fart {
            get {
                return ResourceManager.GetString("fart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Female과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finewood bow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Finewood_bow {
            get {
                return ResourceManager.GetString("Finewood bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fire arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fire_arrow {
            get {
                return ResourceManager.GetString("Fire arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fire resistance barley wine과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fire_resistance_barley_wine {
            get {
                return ResourceManager.GetString("Fire resistance barley wine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FireMagic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FireMagic {
            get {
                return ResourceManager.GetString("FireMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flint axe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Flint_axe {
            get {
                return ResourceManager.GetString("Flint axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flinthead arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Flinthead_arrow {
            get {
                return ResourceManager.GetString("Flinthead arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frost arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Frost_arrow {
            get {
                return ResourceManager.GetString("Frost arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FrostMagic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FrostMagic {
            get {
                return ResourceManager.GetString("FrostMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hair과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hair Colour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hair_Colour {
            get {
                return ResourceManager.GetString("Hair Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   heal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Helmet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Helmet {
            get {
                return ResourceManager.GetString("Helmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Huntsman bow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Huntsman_bow {
            get {
                return ResourceManager.GetString("Huntsman bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inventory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iron atgeir과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Iron_atgeir {
            get {
                return ResourceManager.GetString("Iron atgeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iron axe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Iron_axe {
            get {
                return ResourceManager.GetString("Iron axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iron greaves과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Iron_greaves {
            get {
                return ResourceManager.GetString("Iron greaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iron scale mail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Iron_scale_mail {
            get {
                return ResourceManager.GetString("Iron scale mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ironhead arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ironhead_arrow {
            get {
                return ResourceManager.GetString("Ironhead arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kills과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Kills {
            get {
                return ResourceManager.GetString("Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Knives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Knives {
            get {
                return ResourceManager.GetString("Knives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leather pants과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Leather_pants {
            get {
                return ResourceManager.GetString("Leather pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leather tunic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Leather_tunic {
            get {
                return ResourceManager.GetString("Leather tunic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Long_1 {
            get {
                return ResourceManager.GetString("Long 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Male과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Material과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Megingjord과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Megingjord {
            get {
                return ResourceManager.GetString("Megingjord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Needle arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Needle_arrow {
            get {
                return ResourceManager.GetString("Needle arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No hair과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string No_hair {
            get {
                return ResourceManager.GetString("No hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Obsidian arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Obsidian_arrow {
            get {
                return ResourceManager.GetString("Obsidian arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One Handed Weapon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string One_Handed_Weapon {
            get {
                return ResourceManager.GetString("One Handed Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ooze bomb과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ooze_bomb {
            get {
                return ResourceManager.GetString("Ooze bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Padded cuirass과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Padded_cuirass {
            get {
                return ResourceManager.GetString("Padded cuirass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Padded greaves과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Padded_greaves {
            get {
                return ResourceManager.GetString("Padded greaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pickaxes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pickaxes {
            get {
                return ResourceManager.GetString("Pickaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poison arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Poison_arrow {
            get {
                return ResourceManager.GetString("Poison arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polearms과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Polearms {
            get {
                return ResourceManager.GetString("Polearms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ponytail 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ponytail_1 {
            get {
                return ResourceManager.GetString("Ponytail 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ponytail 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ponytail_2 {
            get {
                return ResourceManager.GetString("Ponytail 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ponytail 3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ponytail_3 {
            get {
                return ResourceManager.GetString("Ponytail 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ponytail 4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ponytail_4 {
            get {
                return ResourceManager.GetString("Ponytail 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rag pants과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Rag_pants {
            get {
                return ResourceManager.GetString("Rag pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rag tunic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Rag_tunic {
            get {
                return ResourceManager.GetString("Rag tunic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shield과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Short_1 {
            get {
                return ResourceManager.GetString("Short 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Short_2 {
            get {
                return ResourceManager.GetString("Short 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shoulder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shoulder {
            get {
                return ResourceManager.GetString("Shoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Side Swept 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Side_Swept_1 {
            get {
                return ResourceManager.GetString("Side Swept 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Side Swept 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Side_Swept_2 {
            get {
                return ResourceManager.GetString("Side Swept 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Side Swept 3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Side_Swept_3 {
            get {
                return ResourceManager.GetString("Side Swept 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silver arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Silver_arrow {
            get {
                return ResourceManager.GetString("Silver arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skills과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skin Colour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Skin_Colour {
            get {
                return ResourceManager.GetString("Skin Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skin Glow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Skin_Glow {
            get {
                return ResourceManager.GetString("Skin Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   slap과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string slap {
            get {
                return ResourceManager.GetString("slap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   slime throw과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string slime_throw {
            get {
                return ResourceManager.GetString("slime throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sneak과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sneak {
            get {
                return ResourceManager.GetString("Sneak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spears과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Spears {
            get {
                return ResourceManager.GetString("Spears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stone axe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Stone_axe {
            get {
                return ResourceManager.GetString("Stone axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swim과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Swim {
            get {
                return ResourceManager.GetString("Swim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swords과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Swords {
            get {
                return ResourceManager.GetString("Swords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Torch {
            get {
                return ResourceManager.GetString("Torch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Troll leather pants과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Troll_leather_pants {
            get {
                return ResourceManager.GetString("Troll leather pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Troll leather tunic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Troll_leather_tunic {
            get {
                return ResourceManager.GetString("Troll leather tunic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trophy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Trophy {
            get {
                return ResourceManager.GetString("Trophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two Handed Weapon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Two_Handed_Weapon {
            get {
                return ResourceManager.GetString("Two Handed Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unarmed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unarmed {
            get {
                return ResourceManager.GetString("Unarmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Utility과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wolf armor chest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Wolf_armor_chest {
            get {
                return ResourceManager.GetString("Wolf armor chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wolf armor legs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Wolf_armor_legs {
            get {
                return ResourceManager.GetString("Wolf armor legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wood arrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Wood_arrow {
            get {
                return ResourceManager.GetString("Wood arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WoodCutting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WoodCutting {
            get {
                return ResourceManager.GetString("WoodCutting", resourceCulture);
            }
        }
    }
}
